version: "3.7"
services:
  nginx:  
    image: "nginx:latest"
    container_name: 'nginx-spa'
    hostname: 'nginx-spa'
    ports: 
      - "7000:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
      - ./node_modules:/mnt/app/node-static
      - ./static:/mnt/app/static

